name = "site-cms"
compatibility_date = "2026-02-19"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "site-cms-db"
database_id = "b14e6638-1d5e-4d32-9a73-25ef4f64110c"

[ai]
binding = "AI"

[vars]
SITE_URL = "https://cms.catiteo.com"
